jobs:
  build:
    runs-on: ubuntu-20.04 # dotnet comes in this tooling machine ? image is a prepared server with everything installed
    steps:
      - uses: actions/checkout@v2.3.1 # github/marketplace/actions
      - run: dotnet build

  test:
  # add needs key
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet test -p:CollectCoverage=true

  analyze:
    needs: [build, test] # tell actions to run analyze until build and test builds
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet tool install --global dotnet-sonarscanner
      - run: | # added the pipe / we have to add build because sonarcloud cant read plain c# but it can read the intermidiate language because it has metadata
          dotnet sonarscanner begin -o:'cvchavez2' -k:'cvchavez2_revature-week4-devops' -d:sonar.login='4b8082d1cbc0691c821359beb0b306299eaec9f' -d:sonar.host.url="https://sonarcloud.io"
          dotnet build
          dotnet test -p:CollectCoverage=true
          dotnet sonarscanner end -d:sonar.login='4b8082d1cbc0691c821359beb0b306299eaec9f'
  # package:
  # deploy: <- jobs

name: build

on: push

# on:
#   push:
#     branches:
#       - master

# person:
#   firstname: 'carlos'
#   lastname: 100 #comment
#   middlename: true 
#   alias:
#     - 'dotnet' # this mean this is a collection
#     - 'lead'