jobs:
  build:
    runs-on: ubuntu-20.04 # dotnet comes in this tooling machine ? image is a prepared server with everything installed
    steps:
      - uses: actions/checkout@v2.3.1 # github/marketplace/actions
      - run: dotnet build

  test:
  # add needs key
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover

  analyze:
    needs: [build, test] # tell actions to run analyze after build and test builds are done
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet tool install --global dotnet-sonarscanner
      - run: | # added the pipe (multiline value) / we have to add build because sonarcloud cant read plain c# but it can read the intermidiate language because it has metadata
          dotnet sonarscanner begin -o:'cvchavez2' -k:'cvchavez2_revature-week4-devops' -d:sonar.login='853311e530df2a0ffeee81fdbe7feaa93459c632' -d:sonar.host.url="https://sonarcloud.io"
          dotnet build
          dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover --logger trx
          dotnet sonarscanner end -d:sonar.login='853311e530df2a0ffeee81fdbe7feaa93459c632'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          # authenticate servers to actually send information
  package:
    env:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    needs: [analyze]
    runs-on: ubuntu-20.4
    steps:
      - uses: actions/checkout@v2.3.1
      - run: echo ${DOCKER_TOKEN} | docker login --username ${DOCKER_LOGIN} --password-stdin
      - run: docker image build -f dockerfile -t devopsci .
      - run: docker image tag devopsci cvchavez2/devopsci
      - run: docker image push cvchavez2/devopsci
      - run: docker logout

    # deploy: <- jobs

name: build

on: push

# on:
#   push:
#     branches:
#       - master

# person:
#   firstname: 'carlos'
#   lastname: 100 #comment
#   middlename: true 
#   alias:
#     - 'dotnet' # this mean this is a collection
#     - 'lead'