jobs:
  build:
    runs-on: ubuntu-20.04 # dotnet comes in this tooling machine ? image is a prepared server with everything installed
    steps:
      - uses: actions/checkout@v2.3.1 # github/marketplace/actions
      - run: dotnet build

  test:
  # add needs key
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet test
  # analyze:
  # package:
  # deploy: empty jobs

name: build

on: push

# on:
#   push:
#     branches:
#       - master

# person:
#   firstname: 'carlos'
#   lastname: 100 #comment
#   middlename: true 
#   alias:
#     - 'dotnet' # this mean this is a collection
#     - 'lead'